name: Docker Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          firstGreeting: "Chris"

      - name: meow
        uses: ./.github/actions/cat-facts
